server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SriyanArosha/sc-config-server
          search-paths:
            - 'service-config-store/*service'
          default-label: master
